language: go

go:
  - "1.10"

env:
  - DEP_VERSION="0.4.1"

install:
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep
  - curl -L -s https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip -o protoc.zip
  - unzip protoc.zip
  - cp -r ./bin/protoc ./include $HOME/bin/
  - make vendor

script:
  - make test